development:
  adapter: postgresql
  encoding: unicode
  database: market_development
  pool: 5
  username: postgres
  password: 1234
  port: 5432
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: market_test
  pool: 5
  username: postgres
  password: 1234

production:
  adapter: postgresql
  encoding: unicode
  database: market_production
  pool: 5
  username: dchoque
  password: dchoque